title: Ice Cubes
email: christinewinter1@gmx.de
description: >- # this means to ignore newlines until "baseurl:"
  A Winter Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.christinewinter.se" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  christinewinter

# Build settings
theme: jekyll-theme-clean-blog
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
